---
- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
- name: "Installing Node Dependencies"
  shell: |
    npm i          


- name: "Pre-start"
  shell: |
      npm install
      pm2 stop default
      pm2 start npm -- start    